default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1


development:
  <<: *default
  database: datatable_development

test:
  <<: *default
  database: datatable_development

test:
  <<: *default
  database: datatable_development